# Generated by Django 6.0.3 on 2026-03-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
